export const EXCHANGE_LANG_FIRST_NAME = 'EXCHANGE_LANG_FIRST_NAME'
export const EXCHANGE_LANG_lAST_NAME = 'EXCHANGE_LANG_lAST_NAME'
export const ADD_ITEM = 'ADD_ITEM'
export const GET_TEST_LIST = 'GET_TEST_LIST'
